using Ksql.Linq.Core.Models;
using System;

namespace Ksql.Linq.Query.Schema;

/// <summary>
/// Definition of Key/Value structures generated by queries
/// </summary>
internal class KeyValueSchemaInfo
{
    public string ClassName { get; set; } = string.Empty;
    public string Namespace { get; set; } = string.Empty;
    public PropertyMeta[] Properties { get; set; } = Array.Empty<PropertyMeta>();
    public string SchemaVersion { get; set; } = "1";
    public string Compatibility { get; set; } = string.Empty;
}