using System.Reflection;
using System.Text;
using Ksql.Linq.Core.Abstractions;
using Ksql.Linq.Query.Ddl;
using Ksql.Linq.Query.Pipeline;

namespace Ksql.Linq.Cli.Services;

/// <summary>
/// Builds KSQL scripts from a KsqlContext's entity models.
/// </summary>
public class ScriptBuilder
{
    private readonly DDLQueryGenerator _ddlGenerator;

    public ScriptBuilder()
    {
        _ddlGenerator = new DDLQueryGenerator();
    }

    /// <summary>
    /// Generates a complete KSQL script from the context.
    /// </summary>
    public string Build(KsqlContext context, ScriptOptions options)
    {
        var sb = new StringBuilder();

        // Generate header
        if (options.IncludeHeader)
        {
            sb.AppendLine(GenerateHeader(options));
            sb.AppendLine();
        }

        // Get all entity models
        var models = context.GetEntityModels();
        if (models.Count == 0)
        {
            sb.AppendLine("-- No entities registered in this context.");
            return sb.ToString();
        }

        // Separate base entities and derived entities
        var baseEntities = new List<EntityModel>();
        var derivedEntities = new List<EntityModel>();

        foreach (var model in models.Values)
        {
            if (model.QueryExpression != null || model.QueryModel != null)
            {
                derivedEntities.Add(model);
            }
            else
            {
                baseEntities.Add(model);
            }
        }

        // Section: Base Streams/Tables (DDL)
        if (baseEntities.Count > 0)
        {
            sb.AppendLine("-- =============================================================================");
            sb.AppendLine("-- BASE STREAMS AND TABLES");
            sb.AppendLine("-- =============================================================================");
            sb.AppendLine();

            foreach (var model in baseEntities.OrderBy(m => m.GetTopicName()))
            {
                sb.AppendLine(GenerateBaseDdl(model, options));
                sb.AppendLine();
            }
        }

        // Section: Derived Streams/Tables (CSAS/CTAS)
        if (derivedEntities.Count > 0)
        {
            sb.AppendLine("-- =============================================================================");
            sb.AppendLine("-- DERIVED STREAMS AND TABLES (CSAS/CTAS)");
            sb.AppendLine("-- =============================================================================");
            sb.AppendLine();

            foreach (var model in derivedEntities.OrderBy(m => m.GetTopicName()))
            {
                sb.AppendLine(GenerateDerivedDdl(model, options));
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private string GenerateHeader(ScriptOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- =============================================================================");
        sb.AppendLine("-- KSQL SCRIPT - Generated by Ksql.Linq");
        sb.AppendLine("-- =============================================================================");
        sb.AppendLine("--");
        sb.AppendLine($"-- Ksql.Linq Version: {GetKsqlLinqVersion()}");
        sb.AppendLine($"-- Assembly: {options.AssemblyName} v{options.AssemblyVersion}");
        sb.AppendLine($"-- Context: {options.ContextTypeName}");
        sb.AppendLine($"-- Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("--");
        sb.AppendLine("-- WARNING: This script was auto-generated. Manual edits may be overwritten.");
        sb.AppendLine("-- =============================================================================");
        return sb.ToString();
    }

    private string GenerateBaseDdl(EntityModel model, ScriptOptions options)
    {
        var sb = new StringBuilder();
        var topicName = model.GetTopicName();

        // Comment with entity info
        sb.AppendLine($"-- Entity: {model.EntityType.Name}");
        sb.AppendLine($"-- Topic: {topicName}");

        // Add topic options comment if available
        var topicOptions = GetTopicOptionsComment(model);
        if (!string.IsNullOrEmpty(topicOptions))
        {
            sb.AppendLine($"-- {topicOptions}");
        }

        // Generate CREATE statement
        var adapter = new EntityModelDdlAdapter(model);
        var streamTableType = model.GetExplicitStreamTableType();

        string ddl;
        if (streamTableType == StreamTableType.Table)
        {
            ddl = _ddlGenerator.GenerateCreateTable(adapter);
        }
        else
        {
            ddl = _ddlGenerator.GenerateCreateStream(adapter);
        }

        // Enhance WITH clause with additional options
        ddl = EnhanceWithClause(ddl, model);

        sb.Append(ddl);
        return sb.ToString();
    }

    private string GenerateDerivedDdl(EntityModel model, ScriptOptions options)
    {
        var sb = new StringBuilder();
        var topicName = model.GetTopicName();

        // Comment with entity info
        sb.AppendLine($"-- Derived Entity: {model.EntityType.Name}");
        sb.AppendLine($"-- Target Topic: {topicName}");

        var queryModel = model.QueryModel;
        if (queryModel != null)
        {
            // Add source info
            if (queryModel.SourceTypes?.Length > 0)
            {
                var sources = string.Join(", ", queryModel.SourceTypes.Select(t => t.Name));
                sb.AppendLine($"-- Source(s): {sources}");
            }

            // Add windows info
            if (queryModel.Windows.Count > 0)
            {
                sb.AppendLine($"-- Windows: {string.Join(", ", queryModel.Windows)}");
            }
        }

        // Add topic options
        var topicOptions = GetTopicOptionsComment(model);
        if (!string.IsNullOrEmpty(topicOptions))
        {
            sb.AppendLine($"-- {topicOptions}");
        }

        // Generate CSAS/CTAS
        var ddl = GenerateCsasCtas(model);
        if (!string.IsNullOrEmpty(ddl))
        {
            sb.Append(ddl);
        }
        else
        {
            sb.AppendLine("-- [Query generation not available - requires runtime analysis]");
        }

        return sb.ToString();
    }

    private string GenerateCsasCtas(EntityModel model)
    {
        var queryModel = model.QueryModel;
        if (queryModel == null)
        {
            return string.Empty;
        }

        var streamTableType = model.GetExplicitStreamTableType();
        var targetName = model.GetTopicName().ToUpperInvariant();

        // Check if this is a windowed aggregation
        if (queryModel.Windows.Count > 0)
        {
            return GenerateWindowedCtas(model, queryModel);
        }

        // For non-windowed, generate basic CSAS/CTAS
        if (queryModel.SourceTypes?.Length > 0)
        {
            var sourceType = queryModel.SourceTypes[0];
            var sourceName = sourceType.GetKafkaTopicName().ToUpperInvariant();

            var prefix = streamTableType == StreamTableType.Table
                ? "CREATE TABLE"
                : "CREATE STREAM";

            return $"{prefix} {targetName} AS SELECT * FROM {sourceName} EMIT CHANGES;";
        }

        return string.Empty;
    }

    private string GenerateWindowedCtas(EntityModel model, Ksql.Linq.Query.Dsl.KsqlQueryModel queryModel)
    {
        var sb = new StringBuilder();
        var targetName = model.GetTopicName().ToUpperInvariant();

        foreach (var window in queryModel.Windows)
        {
            var windowName = $"{targetName}_{window.ToUpperInvariant()}";

            if (queryModel.SourceTypes?.Length > 0)
            {
                var sourceType = queryModel.SourceTypes[0];
                var sourceName = sourceType.GetKafkaTopicName().ToUpperInvariant();

                // Get retention from metadata
                var metadata = model.GetOrCreateMetadata();
                var retentionClause = metadata.RetentionMs.HasValue
                    ? $", RETENTION_MS={metadata.RetentionMs.Value}"
                    : "";

                // Get partitions/replicas
                var partitionsClause = model.Partitions > 0 ? $", PARTITIONS={model.Partitions}" : "";
                var replicasClause = model.ReplicationFactor > 0 ? $", REPLICAS={model.ReplicationFactor}" : "";

                sb.AppendLine($"CREATE TABLE {windowName}");
                sb.AppendLine($"  WITH (KAFKA_TOPIC='{windowName.ToLowerInvariant()}'{partitionsClause}{replicasClause}{retentionClause})");
                sb.AppendLine($"  AS SELECT");
                sb.AppendLine($"    -- [Projection from query model]");
                sb.AppendLine($"  FROM {sourceName}");
                sb.AppendLine($"  WINDOW TUMBLING (SIZE {ParseWindowSize(window)})");
                sb.AppendLine($"  GROUP BY -- [Key columns]");
                sb.AppendLine($"  EMIT CHANGES;");
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    private string ParseWindowSize(string window)
    {
        // Convert timeframe notation to KSQL window size
        // e.g., "1m" -> "1 MINUTE", "5m" -> "5 MINUTES", "1h" -> "1 HOUR"
        if (window.EndsWith("m"))
        {
            var minutes = window.TrimEnd('m');
            return minutes == "1" ? "1 MINUTE" : $"{minutes} MINUTES";
        }
        if (window.EndsWith("h"))
        {
            var hours = window.TrimEnd('h');
            return hours == "1" ? "1 HOUR" : $"{hours} HOURS";
        }
        if (window.EndsWith("d"))
        {
            var days = window.TrimEnd('d');
            return days == "1" ? "1 DAY" : $"{days} DAYS";
        }
        if (window.EndsWith("s"))
        {
            var seconds = window.TrimEnd('s');
            return seconds == "1" ? "1 SECOND" : $"{seconds} SECONDS";
        }

        return window;
    }

    private string EnhanceWithClause(string ddl, EntityModel model)
    {
        // Check if we need to add retention.ms to the WITH clause
        var metadata = model.GetOrCreateMetadata();
        if (!metadata.RetentionMs.HasValue)
        {
            // Also check AdditionalSettings
            if (!model.AdditionalSettings.TryGetValue("retention.ms", out var retVal))
            {
                return ddl;
            }

            if (retVal is string retStr && long.TryParse(retStr, out var retMs))
            {
                return AddRetentionToWithClause(ddl, retMs);
            }
        }
        else
        {
            return AddRetentionToWithClause(ddl, metadata.RetentionMs.Value);
        }

        return ddl;
    }

    private string AddRetentionToWithClause(string ddl, long retentionMs)
    {
        // Find the closing parenthesis of WITH clause
        var withIndex = ddl.LastIndexOf("WITH (", StringComparison.OrdinalIgnoreCase);
        if (withIndex < 0) return ddl;

        var closeParen = ddl.LastIndexOf(')');
        if (closeParen < 0 || closeParen < withIndex) return ddl;

        // Check if retention is already present
        if (ddl.Contains("RETENTION_MS", StringComparison.OrdinalIgnoreCase))
        {
            return ddl;
        }

        // Insert before closing paren
        return ddl.Insert(closeParen, $", RETENTION_MS={retentionMs}");
    }

    private string GetTopicOptionsComment(EntityModel model)
    {
        var parts = new List<string>();

        if (model.Partitions > 0)
        {
            parts.Add($"Partitions: {model.Partitions}");
        }

        if (model.ReplicationFactor > 0)
        {
            parts.Add($"Replicas: {model.ReplicationFactor}");
        }

        var metadata = model.GetOrCreateMetadata();
        if (metadata.RetentionMs.HasValue)
        {
            var hours = metadata.RetentionMs.Value / (1000 * 60 * 60);
            parts.Add($"Retention: {hours}h ({metadata.RetentionMs.Value}ms)");
        }
        else if (model.AdditionalSettings.TryGetValue("retention.ms", out var retVal))
        {
            if (retVal is string retStr && long.TryParse(retStr, out var retMs))
            {
                var hours = retMs / (1000 * 60 * 60);
                parts.Add($"Retention: {hours}h ({retMs}ms)");
            }
        }

        return parts.Count > 0 ? string.Join(", ", parts) : string.Empty;
    }

    private static string GetKsqlLinqVersion()
    {
        var assembly = typeof(KsqlContext).Assembly;
        var version = assembly.GetName().Version;
        return version?.ToString() ?? "0.0.0";
    }

    public class ScriptOptions
    {
        public bool IncludeHeader { get; set; } = true;
        public string AssemblyName { get; set; } = "Unknown";
        public string AssemblyVersion { get; set; } = "0.0.0";
        public string ContextTypeName { get; set; } = "Unknown";
    }
}
