"""
Response formatter for GitHub issue responses
Formats ChatGPT output for GitHub posting
"""

from datetime import datetime
from typing import Optional
import logging

logger = logging.getLogger(__name__)


class ResponseFormatter:
    """Formats responses for GitHub"""

    @staticmethod
    def format_for_github(
        response_text: str,
        issue_number: int,
        include_footer: bool = True,
        bot_signature: Optional[str] = None
    ) -> str:
        """
        Format response for GitHub comment

        Args:
            response_text: Raw response from ChatGPT
            issue_number: Issue number
            include_footer: Add bot footer
            bot_signature: Custom bot signature

        Returns:
            Formatted markdown for GitHub
        """
        parts = [response_text.strip()]

        # Add footer
        if include_footer:
            footer = bot_signature or ResponseFormatter._default_footer()
            parts.append(f"\n\n---\n\n{footer}")

        return "\n".join(parts)

    @staticmethod
    def _default_footer() -> str:
        """Default bot footer"""
        return (
            "*🤖 This response was generated by an AI assistant. "
            "Please verify the information and let me know if you need clarification.*"
        )

    @staticmethod
    def format_draft(
        response_text: str,
        issue_number: int,
        issue_title: str,
        issue_url: str,
        generated_at: Optional[datetime] = None
    ) -> str:
        """
        Format response as draft file

        Args:
            response_text: Raw response
            issue_number: Issue number
            issue_title: Issue title
            issue_url: Issue URL
            generated_at: Generation timestamp

        Returns:
            Formatted draft content
        """
        if not generated_at:
            generated_at = datetime.now()

        header = f"""# Draft Response for Issue #{issue_number}

**Issue:** {issue_title}
**URL:** {issue_url}
**Generated:** {generated_at.strftime('%Y-%m-%d %H:%M:%S')}

---

## Review Checklist
- [ ] Technical accuracy verified
- [ ] Code examples tested
- [ ] Links are correct
- [ ] Tone is appropriate
- [ ] Ready to post

---

## Response Content

"""
        return header + response_text + "\n\n---\n\n**To post this response:**\n```powershell\npython agent.py post-draft --issue " + str(issue_number) + "\n```\n"

    @staticmethod
    def sanitize_markdown(text: str) -> str:
        """
        Sanitize markdown for GitHub

        Args:
            text: Raw markdown text

        Returns:
            Sanitized markdown
        """
        # Remove potentially problematic characters
        # (Add more sanitization as needed)
        return text.strip()

    @staticmethod
    def add_context_references(
        response_text: str,
        related_docs: Optional[list] = None,
        related_issues: Optional[list] = None
    ) -> str:
        """
        Add reference section to response

        Args:
            response_text: Base response
            related_docs: List of documentation URLs
            related_issues: List of related issue numbers

        Returns:
            Response with references
        """
        parts = [response_text]

        if related_docs or related_issues:
            parts.append("\n\n## Additional References\n")

            if related_docs:
                parts.append("\n**Documentation:**")
                for doc in related_docs:
                    parts.append(f"- {doc}")

            if related_issues:
                parts.append("\n**Related Issues:**")
                for issue in related_issues:
                    parts.append(f"- #{issue}")

        return "\n".join(parts)

    @staticmethod
    def format_error_message(
        error_type: str,
        error_details: str,
        issue_number: int
    ) -> str:
        """
        Format error message for logging/notification

        Args:
            error_type: Type of error
            error_details: Error details
            issue_number: Issue number

        Returns:
            Formatted error message
        """
        return f"""
Error processing issue #{issue_number}

Type: {error_type}
Details: {error_details}
Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

    @staticmethod
    def truncate_preview(text: str, max_length: int = 200) -> str:
        """
        Create truncated preview of text

        Args:
            text: Full text
            max_length: Maximum length

        Returns:
            Truncated text with ellipsis
        """
        if len(text) <= max_length:
            return text
        return text[:max_length].strip() + "..."
